### ISSUE TITLE
convert to npm package

### ISSUE THREAD

**Issue by alex9311** [robfallows/tunguska-imgur#2]
hey, great package and blog. Very informative. Would you ever converting this and the `accounts-imgur` package to npm packages? Atmosphere seems to be on the way out

**Comment by robfallows** [comment]
Thanks for the feedback 🙂 

Great question, but this was only ever intended as a guide to the code. The atmosphere package was just a nice little extra - and atmosphere packages still make it so easy to deliver a package with independent client and server components.

TLDR: I'm probably not going to convert this for npm.
